version: '3.9'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: gzg_money
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro
    networks:
      - gzg-money-network
      
  user-service:
    build:
      context: ./user-service/
    ports:
      - "8088:8080"
    volumes:
      - ./user-service/backend:/backend

    environment:
      - DB_HOST=users-database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8080"

    depends_on:
      - users-database     

  gateway-service:
    build:
      context: ./gateway-service/
    ports:
      - "8080:8080"  
    volumes:
      - ./gateway-service/code:/code
    environment:
      - user_service_host=user-service
      - avatars_host=avatars
 
  avatars:
    build:
      context: ./user-service/backend/avatars/
    volumes:
      - ./user-service/backend/avatars/:/usr/share/nginx/html/avatars/
    ports:
     - "8040:80"
    environment:
     - NGINX_PORT=8040
      
  users-database:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
networks:
  gzg-money-network:
    driver: bridge
