openapi: 3.1.0
info:
  title: GZG money
  version: 0.1.0
servers:
  - url: http://localhost:8080
    description: Development server

components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      required: [user_id, username, fullname, email, avatar_url, notifications]
      properties:
        user_id:
          type: string
          format: uuid
        username:
          type: string
        fullname:
          type: string
        email:
          type: string
          format: email
        avatar_url:
          type: string
        notifications:
          type: boolean

    Subscription:
      type: object
      required: [subscription_id, user_id, name, cost, next_billing, status]
      properties:
        subscription_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        name:
          type: string
        cost:
          type: number
          format: double
        next_billing:
          type: string
          example: "2026-03-03"
        status:
          type: boolean
        subscription_avatar_url:
          type: string
          example: "/uploads/41ab2ff8...png"
        category:
          type: string
        url_service:
          type: string
        use_in_this_month:
          type: boolean
        cancellation_link:
          type: string

    AuthTokens:
      type: object
      required: [ access_token, refresh_token, token_type, expires_in ]
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer

    AuthResponse:
      type: object
      required: [ user, tokens ]
      properties:
        user:
          $ref: '#/components/schemas/User'
        tokens:
          $ref: '#/components/schemas/AuthTokens'

    Error:
      type: object
      required: [error, message, timestamp]
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          $ref: '#/components/schemas/ProtoTimestamp'

    ProtoTimestamp:
      type: object
      properties:
        seconds:
          type: integer
        nanos:
          type: integer

    ErrorUserNotFound:
      $ref: '#/components/schemas/Error'
    ErrorInvalidCredentialForSearch:
      $ref: '#/components/schemas/Error'
    ErrorSubscriptionNotFound:
      $ref: '#/components/schemas/Error'

paths:
  /api/user/register:
    post:
      summary: Register new user
      tags: [ Auth ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [username, fullname, email, password, avatar, notifications]
              properties:
                username:
                  type: string
                fullname:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                avatar:
                  type: string
                  format: binary
                notifications:
                  type: boolean
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/user/login:
    post:
      summary: Login user
      tags: [ Auth ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ email, password ]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/user:
    get:
      summary: Get user
      tags: [ User ]
      security:
        - BearerToken: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUserNotFound'

  /api/user/update:
    patch:
      summary: Update user
      tags: [ User ]
      security:
        - BearerToken: [ ]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                email:
                  type: string
                notifications:
                  type: boolean
      responses:
        '200':
          description: Updated

  /api/subscriptions/create:
    post:
      summary: Create subscription
      tags: [ Subscriptions ]
      security:
        - BearerToken: [ ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [name, cost, next_billing, status]
              properties:
                name:
                  type: string
                cost:
                  type: number
                next_billing:
                  type: string
                status:
                  type: boolean
                subscription_avatar:
                  type: string
                  format: binary
                category:
                  type: string
                url_service:
                  type: string
                use_in_this_month:
                  type: boolean
                cancellation_link:
                  type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'

  /api/subscriptions/all:
    get:
      summary: Get subscriptions
      tags: [ Subscriptions ]
      security:
        - BearerToken: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'

  /api/subscriptions/update/{subscription_id}:
    patch:
      summary: Update subscription
      tags: [ Subscriptions ]
      security:
        - BearerToken: []
      parameters:
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                cost:
                  type: number
                next_billing:
                  type: string
                status:
                  type: boolean
                subscription_avatar:
                  type: string
                  format: binary
                category:
                  type: string
      responses:
        '200':
          description: Updated

  /api/subscriptions/delete/{subscription_id}:
    delete:
      summary: Delete subscription
      tags: [ Subscriptions ]
      security:
        - BearerToken: [ ]
      parameters:
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSubscriptionNotFound'
  /api/subscriptions/{subscription_id}:
    get:
      summary: get subscription by id
      tags: [ Subscriptions ]
      security:
        - BearerToken: [ ]
      parameters:
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'