# Generated by Django 4.2.13 on 2026-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_connected_email',
            field=models.BooleanField(default=False),
        ),
    ]
