# Generated by Django 4.2.13 on 2026-02-22 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
