# Generated by Django 4.2.13 on 2026-02-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_url',
            new_name='avatar',
        ),
    ]
