# Generated by Django 4.2.13 on 2026-02-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_avatar_url_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
