# Generated by Django 4.2.13 on 2026-03-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
    ]
